### Trigonometric Functions

In [1]:
import numpy as np 
a = np.array([0,30,45,60,90]) 

print ('Sine of different angles:') 
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180)) 
print ('\n')  

print ('Cosine values for angles in array:') 
print (np.cos(a*np.pi/180)) 
print ('\n')  

print ('Tangent values for given angles:') 
print (np.tan(a*np.pi/180)) 

Sine of different angles:
[ 0.          0.5         0.70710678  0.8660254   1.        ]


Cosine values for angles in array:
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]


Tangent values for given angles:
[  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.73205081e+00
   1.63312394e+16]


In [2]:
import numpy as np 
a = np.array([0,30,45,60,90]) 

print ('Array containing sine values:') 
sin = np.sin(a*np.pi/180) 
print (sin) 
print ('\n')  

print ('Compute sine inverse of angles. Returned values are in radians.') 
inv = np.arcsin(sin) 
print (inv) 
print ('\n')  

print ('Check result by converting to degrees:') 
print (np.degrees(inv)) 
print ('\n')  

print ('arccos and arctan functions behave similarly:') 
cos = np.cos(a*np.pi/180) 
print (cos) 
print ('\n')  

print ('Inverse of cos:') 
inv = np.arccos(cos) 
print (inv) 
print ('\n')  

print ('In degrees:') 
print (np.degrees(inv)) 
print ('\n')  

print ('Tan function:') 
tan = np.tan(a*np.pi/180) 
print (tan)
print ('\n')  

print ('Inverse of tan:') 
inv = np.arctan(tan) 
print (inv) 
print ('\n')  

print ('In degrees:') 
print (np.degrees(inv)) 

Array containing sine values:
[ 0.          0.5         0.70710678  0.8660254   1.        ]


Compute sine inverse of angles. Returned values are in radians.
[ 0.          0.52359878  0.78539816  1.04719755  1.57079633]


Check result by converting to degrees:
[  0.  30.  45.  60.  90.]


arccos and arctan functions behave similarly:
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]


Inverse of cos:
[ 0.          0.52359878  0.78539816  1.04719755  1.57079633]


In degrees:
[  0.  30.  45.  60.  90.]


Tan function:
[  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.73205081e+00
   1.63312394e+16]


Inverse of tan:
[ 0.          0.52359878  0.78539816  1.04719755  1.57079633]


In degrees:
[  0.  30.  45.  60.  90.]


### Rounding

In [3]:
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print ('Original array:') 
print (a) 
print ('\n')  

print ('After rounding:') 
print (np.around(a)) 
print (np.around(a, decimals = 1))
print (np.around(a, decimals = -1))

Original array:
[   1.       5.55   123.       0.567   25.532]


After rounding:
[   1.    6.  123.    1.   26.]
[   1.     5.6  123.     0.6   25.5]
[   0.   10.  120.    0.   30.]


In [4]:
# Floor

import numpy as np 
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:')
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.floor(a))

The given array:
[ -1.7   1.5  -0.2   0.6  10. ]


The modified array:
[ -2.   1.  -1.   0.  10.]


In [5]:
# Ceil

import numpy as np 
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print ('The given array:') 
print (a) 
print ('\n')  

print ('The modified array:') 
print (np.ceil(a))

The given array:
[ -1.7   1.5  -0.2   0.6  10. ]


The modified array:
[ -1.   2.  -0.   1.  10.]


# Arithmetic Functions

In [6]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Second array:') 
b = np.array([10,10,10]) 
print (b) 
print ('\n')  

print ('Add the two arrays:') 
print (np.add(a,b)) 
print ('\n')  

print ('Subtract the two arrays:') 
print (np.subtract(a,b)) 
print ('\n' ) 

print ('Multiply the two arrays:' )
print (np.multiply(a,b)) 
print ('\n')  

print ('Divide the two arrays:' )
print (np.divide(a,b))

First array:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]


Second array:
[10 10 10]


Add the two arrays:
[[ 10.  11.  12.]
 [ 13.  14.  15.]
 [ 16.  17.  18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[  0.  10.  20.]
 [ 30.  40.  50.]
 [ 60.  70.  80.]]


Divide the two arrays:
[[ 0.   0.1  0.2]
 [ 0.3  0.4  0.5]
 [ 0.6  0.7  0.8]]


In [9]:
# Reciprocal

import numpy as np 
a = np.array([0.25, 1.33, 1, 0, 100]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('After applying reciprocal function:') 
print (np.reciprocal(a)) 

Our array is:
[   0.25    1.33    1.      0.    100.  ]


After applying reciprocal function:
[ 4.         0.7518797  1.               inf  0.01     ]


/home/utkarsh/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:11: RuntimeWarning: divide by zero encountered in reciprocal


In [10]:
# Power

import numpy as np 
a = np.array([10,100,1000]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying power function:' )
print (np.power(a,2)) 
print ('\n')  

print ('Second array:') 
b = np.array([1,2,3]) 
print (b) 
print ('\n')  

print ('Applying power function again:' )
print (np.power(a,b))

Our array is:
[  10  100 1000]


Applying power function:
[    100   10000 1000000]


Second array:
[1 2 3]


Applying power function again:
[        10      10000 1000000000]
