# Arrays

In [1]:
# nd-array
# Syntax: numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

#object - Any object exposing the array interface method returns an array, or any (nested) sequence.
#dtype - Desired data type of array, optional
#copy - Optional. By default (true), the object is copied
#order - C (row major) or F (column major) or A (any) (default)
#subok - By default, returned array forced to be a base class array. If true, sub-classes passed through
#ndimin - Specifies minimum dimensions of resultant array

In [3]:
# case 1

import numpy as np 
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [7]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [6]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[ 1.+0.j  2.+0.j  3.+0.j]


# Data Types

In [8]:
#bool_ - Boolean (True or False) stored as a byte
#int_ - Default integer type (same as C long; normally either int64 or int32)
#intc - Identical to C int (normally int32 or int64)
#intp - Integer used for indexing (same as C ssize_t; normally either int32 or int64)
#int8 - Byte (-128 to 127)
#int16 - Integer (-32768 to 32767)
#int32 - Integer (-2147483648 to 2147483647)
#int64 - Integer (-9223372036854775808 to 9223372036854775807)
#uint8 - Unsigned integer (0 to 255)
#uint16 - Unsigned integer (0 to 65535)
#uint32 - Unsigned integer (0 to 4294967295)
#uint64 - Unsigned integer (0 to 18446744073709551615)
#float_ - Shorthand for float64
#float16 - Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
#float32 - Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
#float64 - Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
#complex_ - Shorthand for complex128
#complex64 - Complex number, represented by two 32-bit floats (real and imaginary components)
#complex128 - Complex number, represented by two 64-bit floats (real and imaginary components)

In [9]:
# dtype
#Syntax: numpy.dtype(object, align, copy)

# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print (dt)

int32


In [10]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print (dt) 

int32


In [4]:
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a)

[(10,) (20,) (30,)]


In [12]:
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a['age'])

[10 20 30]


In [13]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print (a)

[(b'abc', 21, 50.0) (b'xyz', 18, 75.0)]


In [14]:
# Below are the representation for the datatypes
#'b' − boolean
#'i' − (signed) integer
#'u' − unsigned integer
#'f' − floating-point
#'c' − complex-floating point
#'m' − timedelta
#'M' − datetime
#'O' − (Python) objects
#'S', 'a' − (byte-)string
#'U' − Unicode
#'V' − raw data (void)

# Array Attributes

In [15]:
# Shape

a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


In [16]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a) 

[[1 2]
 [3 4]
 [5 6]]


In [17]:
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
#ndim

# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [19]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [20]:
# Itemsize

# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [21]:
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

4


# Converting Python data to Numpy Array

In [8]:
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [23]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[ 1.  2.  3.]


In [24]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print (a)

[1 2 3]


In [25]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


# Indexing & Slicing

In [28]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [29]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [30]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print (b)

5


In [31]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [32]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [35]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [36]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a)
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:') 
print (a[...,1]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,...]) 
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
