In [4]:
# Empty

import numpy.matlib 
import numpy as np 

print (np.matlib.empty((2,2))) 
# filled with random data

[[  6.90894643e-310   6.90894643e-310]
 [  6.90893657e-310   6.90893677e-310]]


In [2]:
import numpy.matlib 
import numpy as np 
print (np.matlib.zeros((2,2)))

[[ 0.  0.]
 [ 0.  0.]]


In [3]:
import numpy.matlib 
import numpy as np 
print (np.matlib.ones((2,2)))

[[ 1.  1.]
 [ 1.  1.]]


In [4]:
import numpy.matlib 
import numpy as np 
print (np.matlib.eye(n = 3, M = 4, k = 0, dtype = float))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


In [5]:
import numpy.matlib 
import numpy as np 
print (np.matlib.identity(5, dtype = float))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [6]:
import numpy.matlib 
import numpy as np 
print (np.matlib.rand(3,3))

[[ 0.80887898  0.12848428  0.00983262]
 [ 0.62900738  0.54370907  0.86539024]
 [ 0.25897104  0.37420048  0.78357286]]


In [7]:
#converting an array into matrix
import numpy.matlib 
import numpy as np  

i = np.matrix('1,2;3,4') 
print (i) 

[[1 2]
 [3 4]]


In [8]:
import numpy.matlib 
import numpy as np  

j = np.asarray(i) 
print (j) 

[[1 2]
 [3 4]]


In [9]:
import numpy.matlib 
import numpy as np  

k = np.asmatrix (j) 
print (k)

[[1 2]
 [3 4]]
