In [1]:
# Minimum & Maximum

import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:') 
print (a)  
print ('\n')  

print ('Applying amin() function:') 
print (np.amin(a,1)) 
print ('\n')  

print ('Applying amin() function again:') 
print (np.amin(a,0)) 
print ('\n')  

print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n')  

print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


In [3]:
# Median

import numpy as np 
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying median() function:')
print (np.median(a)) 
print ('\n')  

print ('Applying median() function along axis 0:') 
print (np.median(a, axis = 0)) 
print ('\n')  
 
print ('Applying median() function along axis 1:' )
print (np.median(a, axis = 1))

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying median() function:
65.0


Applying median() function along axis 0:
[ 50.  90.  60.]


Applying median() function along axis 1:
[ 65.  80.  60.]


In [4]:
# Mean

import numpy as np 
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying mean() function:')
print (np.mean(a)) 
print ('\n')  

print ('Applying mean() function along axis 0:') 
print (np.mean(a, axis = 0)) 
print ('\n')  
 
print ('Applying mean() function along axis 1:' )
print (np.mean(a, axis = 1))

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying mean() function:
61.1111111111


Applying mean() function along axis 0:
[ 53.33333333  83.33333333  46.66666667]


Applying mean() function along axis 1:
[ 55.          61.66666667  66.66666667]


In [5]:
#Standard Deviation

import numpy as np 
print (np.std([1,2,3,4]))

1.11803398875


In [6]:
#variance

import numpy as np 
print (np.var([1,2,3,4]))

1.25
